python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
exit
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
exit
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
clear
exit
